# -*- coding: utf-8 -*-
"""Day1 calculator Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AapjhaLbaeQWI4-vii1cgj964Ld47YoK
"""

import numpy as np

print("====CALCULATOR====")
a=float(input("enter first element"))
b=float(input("enter second element"))
op=(input("choose(+,-,*,/):"))

if op =="+":
  print("Result =",np.add(a,b))
elif op =="-":
  print("Result =",np.subtract(a,b))
elif op =="*":
  print("Result =",np.multiply(a,b))
elif op =="/":
  print("Result =",np.divide(a,b))
else:
  print("Invalid Operations")