# -*- coding: utf-8 -*-
"""Day2 pandas series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qmk-6OWwF-ySx8vdwJASmRKlZE8Pv7E9
"""

import numpy as np
import pandas as pd

data = pd.read_csv("/content/ai-impact-jobs-layoff-risk-dataset.csv")

data.value_counts()

data.info()

data.head(2)

data.sample()

data.count()

data.sum()

data.describe()

data.shape

data.iloc[-1]

data["Age"]=0
data

