# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSyroSZr1J95z-mIMPM9B5m3rJJ0DTqO
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

price = [4800,54000,4800,54000,48000,5400]
year = [2015,2016,2017,2018,2019,2020]
plt.plot(year,price)

batsman = pd.read_csv("/content/sharma-kohli.csv")
batsman

plt.plot(batsman['index'],batsman['V Kohli'])

plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])

plt.plot(batsman['index'],batsman['V Kohli'])
plt.plot(batsman['index'],batsman['RG Sharma'])
plt.title("V Kohli vs RG Sharma")
plt.xlabel("Season")
plt.ylabel("Runs")

plt.plot(batsman['index'],batsman['V Kohli'],color='#D9F10F')
plt.plot(batsman['index'],batsman['RG Sharma'],color='#FC00D6')
plt.title("V Kohli vs RG Sharma")
plt.xlabel("Season")
plt.ylabel("Runs")

batsman = pd.read_csv("/content/fours-sixes.csv")
batsman

plt.bar(batsman['season'],batsman['Fours'], label='Virat',color = '#03fce3' , linestyle = "dashdot" )
plt.bar(batsman['season'],batsman['Sixes'], label='Rohit',color = 'red' , linestyle = "dotted" )
plt.title("Fours vs Sixes per Season")
plt.xlabel("Season")
plt.ylabel("Count")
plt.legend()

x = np.linspace(-10,10,50)
y = 10*x + + np.random.randint(0,300,50)
y

a = pd.read_csv("/content/archive.zip")
a

plt.plot(a['Date'], a['Volume'])

plt.scatter(x,y)

s = pd.read_csv("/content/batter.csv")
s = s.head(50)
s

plt.scatter(s['avg'],s['strike_rate'],color='red')
plt.title("Average vs Strike Rate")
plt.xlabel("Average")
plt.ylabel("Strike Rate")

#size
tips=sns.load_dataset('tips')

#slower
plt.scatter(tips['total_bill'],tips['tip'],s=tips['size']*20)

"""## **BAR CHART**"""

import matplotlib.pyplot as plt

# 1. Your data (7 elements)
children = [10, 20, 30, 40, 30, 20, 10]

# 2. X-axis labels (Must also be 7 elements to match 'children')
categories = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5', 'Day 6', 'Day 7']

# 3. Your color list (7 elements)
bar_colors = ['red', 'green', 'blue', 'yellow', 'orange', 'pink', 'brown']

# 4. Pass categories first, then the values, then the colors
plt.bar(categories, children, color=bar_colors)

# Display the plot
plt.show()

